### ISSUE TITLE
MSI: Add Chocolatey package

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#12]
Chocolatey is a modern package management system (like apt or yum on GNU/Linux) for Windows: https://chocolatey.org/

Most packages for this system is implemeted as a wrapper of an original installer (.msi or .exe).
I'm also planning to use same way to implement td-agent package for it.

**Comment by ashie** [comment]
FYI: Microsoft unveils a new package management system: https://github.com/microsoft/winget-cli

**Comment by cosmo0920** [comment]
Currently, executables of winget is not provided but the package definition syntax is very easy.
cf.) https://github.com/microsoft/winget-pkgs/blob/6c25507a41ac82587513ae093e0e33d93c235858/manifests/PuppetLabs/puppet/3.8.7.0.yaml

**Comment by cosmo0920** [comment]
winget provides CLI tool to generate manifest.
I tested it and it generated the following manifest for td-agent:

```yaml
Id: TreasureData.TDAgent
Version: 4.0.0
Name: TD-Agent
Publisher: Treasure Data Inc.
License: Apache Lincense 2.0
LicenseUrl: https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/LICENSE
AppMoniker: td-agent
Tags: fluentd, logging
Description: Treasure Agent: A data collector for Treasure Data
Homepage: https://www.fluentd.org
Installers:
  - Arch: x64
    Url: http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.0.0-x64.msi
    Sha256: 752DA24B7B4C39C48F3EE66A87A109FC97C7627BAFFD63BD95A5D193296322F8
    InstallerType: msi
```

**Comment by cosmo0920** [comment]
I think that creating winget package is easier than creating chocolatey package.

**Comment by cosmo0920** [comment]
I'd confirmed that the following manifest can proceed td-agent installation:

```yaml
Id: TreasureData.TDAgent
Version: 4.0.0
Name: TD-Agent
Publisher: Treasure Data Inc.
License: Apache Lincense 2.0
LicenseUrl: https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/LICENSE
AppMoniker: td-agent
Tags: fluentd, logging
Description: "Treasure Agent: A data collector for Treasure Data"
Homepage: https://www.fluentd.org
Installers:
  - Arch: x64
    Url: http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.0.0-x64.msi
    Sha256: 752DA24B7B4C39C48F3EE66A87A109FC97C7627BAFFD63BD95A5D193296322F8
    InstallerType: msi
    Switches:
      Silent: "/quiet"
      SilentWithProgress: "/quiet /passive"
```

But we should this task after td-agent 4.0.1 is released. Because td-agent 4.0.0 has a pitfall to prevent C extension building due to lack of dll.a which is one of the needed component for building C extension with MSYS2.
